### ISSUE TITLE
Copy number variations input

### ISSUE THREAD

**Issue by jelisavetailic** [ncsa/NEAT#10]
Hi,

I see that in gen_reads.py, one of the outputs is golden VCF file which includes variants which will be present in golden BAM file. One of the lines in header of that VCF file is: 
##ALT=<ID=CNV,Description="Copy number variable region">

Is there a way to insert copy numbers into generated BAM file? For example, to provide an input with copy number regions and their numbers (ex. chr1 1 100 7 - where columns are: chromosome, start, end, copy number) or something similar which will output golden BAM file and information about copy number variations?

Thank you!

**Comment by joshfactorial** [comment]
It's possible, though not quite as you have it here. The only way to do it at the moment would be to create a vcf with the full copy number variant in it, and use that as an input vcf. NEAT will try to insert all variants from the input vcf (-v flag).

**Comment by jelisavetailic** [comment]
Thank you!
