### ISSUE TITLE
Stuck in the “Covering dataset” step when changing default read length 

### ISSUE THREAD

**Issue by dani-ture** [ncsa/NEAT#116]
**Describe the bug**

I have set read_len: 100 and to 125 to do some testing again with the E. coli genome and after 3 days `neat read-simulator` is still stuck in the “Covering dataset” step. 

**To Reproduce**

1. Download the E. coli NCBI RefSeq assembly from the following link: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000005845.2/
2. Make a copy of the provided template config file (I called it test_config.yml) and set the parameters:
    
    ‘’’reference: GCF_000005845.2_ASM584v2_genomic.fna
    
    ploidy: 1
    
    read_len: 100
    
    rng_seed: 6386514007882411’’’
    
    The rest are left with the “.” as default.
    
3. Run neat on the command line:`neat --log-name test --log-detail HIGH --log-level DEBUG read-simulator -c test_config.yml -o test`

**Expected behavior**

I expected neat to give me some fastq file in more or less the same time as when using default parameters. 

**Desktop:**

- OS: Linux
- Browser: Chrome
- Version: 4.2.1

**Comment by joshfactorial** [comment]
Apologies, sounds similar to a bug we're working on. We will hopefully have a new version ready as soon as this week that i think will clear this up.

**Comment by dani-ture** [comment]
Great, thank you.

**Comment by joshfactorial** [comment]
I believe this is now resolved in the latest release. Please reopen the ticket if you have further issues.
