### ISSUE TITLE
Inconsistent coverage with high depth (> 20,000X)

### ISSUE THREAD

**Issue by lbeltrame** [ncsa/NEAT#13]
**Describe the bug**
I'm not sure it is a bug, but as far as I can see the random variations in coverage can become very large with high depth datasets.

Background: we're testing sensitivity of variant callers in high-depth, very low allele fraction scenarios. We're using NEAT to generate the reads: a typical scenario expects around ~25,000X-30,000X coverage. Our approach is also focused, so we have a BED file with the regions we are interested in.

The issue (or perhaps working as intended, I don't know) is that NEAT is very variable at such high coverages. We tried with two depths: 

- 25,000X - after alignment with bwa-mem and measurement of coverage (with mosdepth) yields ~14K
- 30,000X - we have around 18K coverage or so

The options we used NEAT with:

```
 -R 150 \
--pe 192 37 \ # Determined from our existing data
-c 30000 \ # or 250000
 -E 0.004 \ # From sequencing data 
-tr ${BED} \ 
-M 0.002 
```

The question is: is such a behavior a feature and not a bug? Do we have to push coverage much higher to actually get close to our estimated amount?

**To Reproduce**
1. Generate FASTQ with NEAT at high depth
2. Align against hg38 with bwa-mem
3. Measure coverage with mosdepth

**Expected behavior**
A median coverage closer to the actual value specified.

**Comment by joshfactorial** [comment]
If you are using a targeted bed file, then the coverage should be on average 30k/25k in those regions, but default levels outside that, which is 2% of the targeted region value. You can control the off-target coverage with the -to  flag.
