### ISSUE TITLE
neat crashes with target_bed file > 500 lines

### ISSUE THREAD

**Issue by destinymullens** [ncsa/NEAT#130]
**Describe the bug**
I am attempting to simulate mouse reads using GRCm39. I was to do this successfully with a test run with default settings and the downloaded genome. I have created a BED file containing only exons but when trying to run using the BED file and off_target_scalar, it crashes.

**To Reproduce**
1. Used mouse genome (GCF_000001635.27_GRCm39)
2. Created BED file with only exons
3. Used config file with values:
- reference: <path-to-genome-file>
- coverage: 2
- target_bed: <path-to-BED-file>
- off_target_scalar: 0.01
- produce_bam: true
- produce_fastq: true
6. Ran neat command on command-line
7. neat crashes

**Additional context**
For my own troubleshooting to see if it was related file formatting or maybe one line:
- I first limited the BED file to 100 lines. It ran fine.
- I increased the BED file to 1000 lines. It crashed
- I tried again with 500 lines, hoping maybe I had a formatting error somewhere. While it was running, I noticed really high memory usage (screenshot below). Once it exceeded the memory on the machine, it obviously crashes so that seems to be the issue.

**Screenshots**
![neat-memory-usage](https://github.com/user-attachments/assets/8812c917-488f-4830-9654-94349f386d10)

**Desktop (please complete the following information):**
Ubuntu 22.04, 126 GB usable RAM

Is this an issue with memory allocation or do I need to limit the number of lines in my BED file unless I am on a machine with more RAM available?

**Comment by joshfactorial** [comment]
It could well be a memory issue, depending on the size of the input genome. I will try to replicate this error and see if there is a memory leak somewhere during the bed process.

**Comment by destinymullens** [comment]
Thank you! I attempted with just a single chromosome as well and had issues until I limited the number of lines in the BED file. If you’d like me to upload the exact files I was using, please let me know.

**Comment by joshfactorial** [comment]
That would be helpful, or if you have a link where I can download it, either way.
________________________________

**Comment by destinymullens** [comment]
Here are the files I was using for the last run that crashed: 
[Reference](https://gofile.me/73VRL/afJaqs0CM)
[BED file](https://gofile.me/73VRL/Wdn0bFSZD)

I have edited that reference to remove any non-localized scaffolds and the MT chromosome and the BED file is the first 500 lines of exons.

**Comment by joshfactorial** [comment]
I'm seeing the same thing, even on a single chromosome file. It does run on Chromosome Y, but that seems to be because there are no bed records associated with it. It also looks like we may be copying pieces of the reference within the code, which is why the memory explodes. I will work on a better solution for this.

**Comment by joshfactorial** [comment]
I changed the way it uses the reference in the bed function. I think that's what was causing the slowdown, and it seems resolved on my computer. I was able to run chromosome 1 to completion. Please check out the develop branch and see if that fixes it (`git checkout develop`) If it seems resolved for you, I will merge that and do a new release.

**Comment by joshfactorial** [comment]
I realized I used a truncated bed, but trying again with the full bed, it read the bed almost instantaneously, which was more what I was expecting. Hopefully the results are good! Please let us know if you notice anything incorrect or weird in the data once the run completes.

**Comment by destinymullens** [comment]
Thank you!! I will try to checkout the develop branch this morning and see how it goes!

**Comment by destinymullens** [comment]
It has loaded the full bed file and started simulating the reads! Thank you so much!

**Comment by huguesrichard** [comment]
Hello,

I noticed a problem that I think is related. I am simulating exome from chr8 in Human, and when I add an off target option (here 0.10). With 64G of RAM allocated on the cluster  the process gets killed before the read generation. It is working if I lower down the off target option to 0.0.

**Comment by joshfactorial** [comment]
Yes, we would do it programmatically. The changes in NEAT 4.0 were made to address other shortcomings of the code, but is still a work in progress.
