### ISSUE TITLE
Paired-end reads have identical sequence

### ISSUE THREAD

**Issue by WackerO** [ncsa/NEAT#17]
Hello,

**Describe the bug:**

I would like to use neat for the simulation of targeted paired-end read sequencing. For some reason though, about half of the generated read pairs have the same sequence for forward and reverse (i.e. in read pair 1, the forward read sequence == reverse read sequence). As I set the fragment length to about 400 (previously 272, which produced the same result), I was expecting no overlap to exist, but instead, the reads overlap completely.
It also seems that such read pairs are not written into the golden BAM produced by the --bam flag.

**To Reproduce**

I used the following command:

python NEAT/gen_reads.py -c 5000 -r GRCh37_sub.fa -R 101 -o neat_output/neat_5k_272_15_hotspots_cancer -tr neat_input/regions.bed --pe 400 15 --bam -M 0 -E 0 -to 0

The refrence genome is a subset of GRCh37 containing only chromosomes 1, 2 and 3; the bed file simply contains one target region:
chr1	10000	12000

**Expected behavior**

To not find any read pairs in which the forward and reverse read have an identical sequence

**Comment by joys8998** [comment]
Hi @WackerO,

I didn't noticed that and maybe this is the reason why gold bam file is way different from the aligned bam file created by running bwa-mem2 and samtools from the fastq files. (https://github.com/ncsa/NEAT/issues/16#issue-953374685)

**Comment by WackerO** [comment]
Hey @joys8998,

yes, I imagine that might at least contribute to the differences in your alignments. However, I found that usually, around half of the read pairs are incorrectly generated; in your case, it seems only about a third of the mappings are incorrect. Did you check if your neat run also generates read pairs with identical sequences? Your error might, after all, be another one.

**Comment by MeatKatlet** [comment]
Hello. I noticed this behavior too. I fixed it and make pull request [here](https://github.com/ncsa/NEAT/pull/24)

**Comment by joshfactorial** [comment]
Thank you! Good catch!
