### ISSUE TITLE
Pickle error

### ISSUE THREAD

**Issue by MikeWLloyd** [ncsa/NEAT#44]
I cloned the repo, and am trying to run the base command. 

I get the following error: 

```
NEAT/source/SequenceContainer.py", line 872, in __init__
    error_dat = pickle.load(open(model_path, 'rb'), encoding="bytes")
_pickle.UnpicklingError: invalid load key, '\x1f'.
```

Can you advise?

**Comment by joshfactorial** [comment]
If you're using the master branch, then yes, I recoded the model files as gzipped pickle files. I was just in the process of cleaning up the code related to that and just pushed the fix for this problem. Let me know if you see it again. Please include your run command if so.

**Comment by MikeWLloyd** [comment]
This is perhaps the fastest commit I have ever experienced with such a tool! Amazing. Fixed this issue. 

Having a separate issue now when running on chrM. Will post a new ticket for that.

**Comment by joshfactorial** [comment]
haha, I had just noticed the same error
