### ISSUE TITLE
Odd behaviour with overlapping probes in target region file

### ISSUE THREAD

**Issue by jeffpbruce** [ncsa/NEAT#5]
**Describe the bug**
No reads are generated when there is a series of regions that overlap in the target regions file.

**To Reproduce**
Run gen_reads.py with a bed file that has overlapping regions. 

**Screenshots**
<img width="490" alt="Screen Shot 2021-03-29 at 8 58 29 PM" src="https://user-images.githubusercontent.com/9290719/112918274-855e1700-90d2-11eb-8bae-0dce0c1f629e.png">

**Comment by jeffpbruce** [comment]
A sample bed file to reproduce the issue: [sample.bed](https://drive.google.com/file/d/11x8laPQHdx17A7yTSi5_p8pnqaSlotVJ/view?usp=sharing)

**Comment by joshfactorial** [comment]
I will investigate this issue.

**Comment by joshfactorial** [comment]
I tried a small sample with an overlapping bed, but was not able to reproduce this error. Can you give me the exact command you used? Thanks!

**Comment by jeffpbruce** [comment]
Thanks for looking into it - here is a command that produces a similar result to that above:

python gen_reads.py -E 0 -M 0 \
-r chr17.fa \
-R 179 -c 15.8016371886693 \
-o BUG_TEST_simulated_16960_179_bp_reads \
--bam --vcf -tr sample.bed

Note: I used chr17.fa alone to speed up the process, the same occurs when the entire reference is used.

**Comment by joshfactorial** [comment]
Okay, I ran this test and checked against the bed file for this phenomenon. What I found was that the regions where there was zero coverage were the areas outside the bed file. For example, I'm seeing no coverage in the space 41,239,500 or so to about 41,240,000. In the bed file, the targeted regions are:

chr17    41239246     41239366
chr17    41240086     41240206

I re-ran the test setting -to (for off-target coverage scalar) to 1. It's a percentage, so that should give me full coverage on the uncovered regions:

![bug_test](https://user-images.githubusercontent.com/26775531/116609145-aa27f300-a8f9-11eb-855b-2bdd9a8a7c31.png)

So it looks to me like it's behaving as intended for targeted regions. Let me know if you have any other question.

**Comment by jeffpbruce** [comment]
The regions in the screen shot you show above are not actually overlapping (just appear so due to the scale I believe). Can you check this region in your bam: chr17:41,236,647-41,252,815 ? It's where there is a large exon that results in end-to-end regions in the bed (that I think are the issue). Sorry, I should have mentioned that region to begin with.

Thanks for looking into this.

**Comment by joshfactorial** [comment]
Sorry, I'm still not seeing what you're describing. I looked at the bed file in that region and I see an overlap here:

chr17   41242846        41242966        665792_30954068_BRCA1(672)_289  0       -
chr17   41242944        41243064        659063_29806789_HBOC_BRCA1_1    0       +

![bug_test2](https://user-images.githubusercontent.com/26775531/116719453-b31fcf80-a9a0-11eb-876d-c1be7fa7e2ee.png)

But I'm not seeing any gap. Are you using the most recent version of the repo? The master branch has a couple of bug fixes not in the release version. I also found a potential bug in one of the bed file steps that I don't think would have come into play, but it may be worth pulling in all the latest updates and running again. I was using ch17 from the latest ucsc hg19. I also tried running it again in python 3.7 (v 3.8) and sorting the bed to see if that has any effect on the output, but it looks the same to me.

```
./gen_reads.py \
-r hg19.chr17.fa \
-E 0 -M 0 -R 179 \
-o Bug_test_3 \
--vcf --bam \
-tr sample.sorted.bed \
-c 15.8016371886693 \
```

**Comment by jeffpbruce** [comment]
I think it may be specifically end to end regions rather than overlaps.  Can you check exactly this region? chr17:41,236,647-41,252,815

**Comment by joshfactorial** [comment]
I have noticed this behavior in other places. I think what it is, is that NEAT uses a blacklist to try to avoid overlapping variants and so the reads have these weird artificial gaps. This is something we'll seek to improve with new releases.
