### ISSUE TITLE
Insertion of CNVs

### ISSUE THREAD

**Issue by lukatop** [ncsa/NEAT#62]
Hi, thanks for the great tool!

I saw the issue here about inserting CNVs which should be provided in a VCF and given with: -v option. I tried doing that, but I can see  that these variants will be skipped as they don't contain ACTG in ALT field.

```
reading input VCF...

found 247 valid variants in input vcf.
 * 0 variants skipped: (qual filtered / ref genotypes / invalid syntax)
 * 1 variants skipped due to multiple variants found per position
--------------------------------
reading EB0001...
20.439 (sec)
found 219 valid variants for EB0001 in input VCF...
7 variants skipped...
 - [0] ref allele does not match reference
 - [0] attempting to insert into N-region
 - [7] alt allele contains non-ACGT characters
```

I tried two different lines, with format of CNV: 

> EB0001	1087750	.	C	< CNV >	.	PASS	SVTYPE=CNV;END=1090600;SVLEN=2850;Ploidy=1;DP=117	GT:DP:CN:AF	1:83:2:1
> EB0001	1087750	.	C	CNV	.	PASS	SVTYPE=CNV;END=1090600;SVLEN=2850;Ploidy=1;DP=117	GT:DP:CN:AF	1:83:2:1

In both cases it complains about ALT non-ACTG alleles. Can you provide an example of the CNV line in the VCF format you got it working?

**Comment by joshfactorial** [comment]
I think the only way to do this at this point would be to manually write out the CNV, like

`EB0001 1087750 . C CCCCCCCCCCCCCCCCCCCCCCC . PASS ... etc`

Is what you have the standard way of notating CNVs? If so, I can see if we can incorporate that into a future update.

**Comment by lukatop** [comment]
Hi @joshfactorial for the fast response. I don't think this is a standard way, since there are a lot of ways to represent CNVs, I tried this one as it was the easier for me to test. GATK has a little bit different representation: 
![image](https://user-images.githubusercontent.com/106684627/188163187-7eb2333a-51e0-4087-854f-e1b29592fe28.png)

Also, some tools like CNVkit or ControlFreec are outputting TSV files. Anyway you add it will be fine. Current implementation could be troublesome for larger CNVs: 2k bp or more. 
Best,
Luka

**Comment by joshfactorial** [comment]
Sounds good. We’ll look into this more. We might be able to implement as part of NEAT 4.1, but probably not the 4.0 release.

-Josh

**Comment by joshfactorial** [comment]
We're investigating reading in CNVs from an input VCF for NEAT version 4.0

**Comment by joshfactorial** [comment]
Added to the backlog
