### ISSUE TITLE
Parallel simulations

### ISSUE THREAD

**Issue by Anushi** [ncsa/NEAT#8]
Hi, Does version 3 still have parameter to parallelize the gen_reads.py for whole genomes? I used "--job" parameter for version 2 for parallelizing simulation. Thanks.

**Comment by joshfactorial** [comment]
It doesn't at the moment. We're investigating the best way to re-implement this. You can manually split your input fasta and combine the results at the end using cat or samtools.

**Comment by sushma-4** [comment]
Hi @Anushi, 

Could you give more details about what you're expecting from the --job parameter and how utilized it previously?
