### ISSUE TITLE
Installation failure due to version conflicts

### ISSUE THREAD

**Issue by linxy29** [ncsa/NEAT#83]
**Describe the bug**
I tried to install the current version of NEAT and came across the error 'ERROR: Package 'neat' requires a different Python: 3.8.8 not in '<4.0,>=3.10' '.

**To Reproduce**
1. git clone NEAT repo
2. enter the NEAT directory
3. follow instruction to install NEAT
> conda env create -f environmental.yml -n neat
> conda activate neat
> poetry build
> pip install dist/neat*whl

**Expected behavior**
I assumed this error was caused by version conflicts in different files. Could anyone help with this or indicate the installation instructions for a previous stable version? Thank you

**Comment by joshfactorial** [comment]
Due to some compatability issues, this version of NEAT had a Python v3.10 requirement. If this is not possible, you can check out tagged versions or look at the releases to download files directly.

**Comment by joshfactorial** [comment]
We're working on building a container, as a solution, that will hopefully help with installation issues.

**Comment by joshfactorial** [comment]
Can we get some info on what OS you are using, what step gave you the error? I was unable to replicate on a baseline Ubuntu install. Which version of conda did you use? I've had problems occasionally with miniconda, so there may be an underlying dependency issue there.

**Comment by linxy29** [comment]
Thanks for your help. It works after I specify the Python version as 3.10.  I replaced `conda env create -f environmental.yml -n neat` with `conda env create -f environment.yml -n neat python=3.10`. By the way, the yml file name should be 'environment.yml'.

**Comment by joshfactorial** [comment]
I corrected that on the main branch. Thanks!
________________________________
