### ISSUE TITLE
Rough timeline until stable release of NEAT 4

### ISSUE THREAD

**Issue by wm75** [ncsa/NEAT#93]
First of all thank you for developing and maintaining NEAT :yellow_heart: 

Since the latest bug reports and develop changes I've seen for NEAT 4 are a few months old by now, I'm wondering whether you can provide an approximate timeline for when you think you will produce a stable release of NEAT 4?

You've been pointing people to the stable NEAT 3 before, but will this be the way to go for the foreseeable future, or will NEAT 4 be ready to take over soonish?

Thanks for any information :-)

**Comment by joshfactorial** [comment]
We're still trying to test things on 4.0, mostly working behind the scenes. If you want to try the develop branch, it's going in the right direction. The main thing I need to tackle is a marked slowdown for higher levels of coverage. I'm going to rework the coverage section soon (when I can buy some time). I think that is the last major hurdle before 4.0 is fully ready. I'm hoping this week or next to sit down and do that.

**Comment by joshfactorial** [comment]
We're also working on getting access to some compute resources to test on larger datasets. most of the testing so far has been confined to viral and yeast samples that will run on a laptop.

**Comment by joshfactorial** [comment]
We are feeling confident about the stability of the 4.1 release! Please try out the latest version and let us know what you think. We will respond to any bugs as quickly as possible!

**Comment by wm75** [comment]
Nice! Bioconda package for it is out: https://github.com/bioconda/bioconda-recipes/pull/46708.
Will start testing ...

**Comment by joshfactorial** [comment]
o.O

**Comment by joshfactorial** [comment]
I didn't know that was happening!

**Comment by wm75** [comment]
Well, the bigger picture here is that I would like to have neat 4 available on Galaxy and a first step towards that is having a conda package / biocontainer for it because that's what Galaxy tools rely on under the hood.
So I thought that while waiting for a stable release I could also just create the bioconda recipe, and now it's getting updated semi-automatically on new releases.
